version: "3.8"

services:
  backend:
    build: ./backend
    container_name: express-backend
    working_dir: /app       
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DATABASE_URL: mysql://root:password@db:3306/portfolio_db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: portfolio_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
